export const items = [
//   {
//     id: 1,
//     title: 'BLUSA CASUAL TELA OXFORD 65% ALG – 35% POL',
//     description: 'Blusa Casual confeccionada en tela Oxford 65% Alg – 35% Pol, asiluetada, manga larga, botones en puños. Con Pie de cuello y puños mil rayas / marino.',colors: 'Azul cielo, Azul marino, Blanco, Rosa',
//     sizes: 'CH, MD, GD, XG',
//     category: 'Casual',
//     subcategory: 'Camisas',
//   },
//   {
//     id: 2,
//     title: 'BLUSA CASUAL TELA OXFORD 65% ALG – 35% POL',
//     description: 'Blusa Casual confeccionada en tela Oxford 65% Alg – 35% Pol, asiluetada, manga corta, botones en puños. Con Pie de cuello y puños mil rayas / marino.',colors: 'Azul cielo, Azul marino, Blanco, Rosa',
//     sizes: 'CH, MD, GD, XG',
//     category: 'Casual',
//     subcategory: 'Camisas',
//   },
//   {
//     id: 3,
//     title: 'BLUSA CASUAL TELA OXFORD MIL RAYAS 65% ALG – 35% POL',
//     description: 'Blusa Casual confeccionada en tela Oxford 65% Alg – 35% Pol, asiluetada, manga larga, botones en puños.',colors: 'Azul cielo, Azul marino, Rojo, Verde',
//     sizes: 'CH, MD, GD, XG',
//     category: 'Casual',
//     subcategory: 'Camisas',
//   },
//   {
//     id: 4,
//     title: 'CAMISA CASUAL TELA OXFORD 65% ALG – 35% POL',
//     description: 'Camisa Casual confeccionada en tela Oxford 65% Alg – 35% Pol, manga larga, botones en cuello y puños. Con Pie de cuello y puños mil rayas / marino.',colors: 'Azul cielo, Azul marino, Blanco, Rosa',
//     sizes: '34, 36, 38, 40, 42, 44',
//     category: 'Casual',
//     subcategory: 'Camisas',
//   },
//   {
//     id: 5,
//     title: 'CAMISA CASUAL TELA OXFORD 65% ALG – 35% POL',
//     description: 'Camisa Casual confeccionada en tela Oxford 65% Alg – 35% Pol, manga corta, botones en cuello y puños. Con Pie de cuello y puños mil rayas / marino.',colors: 'Azul cielo, Azul marino, Blanco, Rosa',
//     sizes: '34, 36, 38, 40, 42, 44',
//     category: 'Casual',
//     subcategory: 'Camisas',
//   },
//   {
//     id: 6,
//     title: 'CAMISA CASUAL TELA OXFORD MIL RAYAS 65% ALG – 35% POL',
//     description: 'Camisa Casual confeccionada en tela Oxford 65% Alg – 35% Pol, manga larga, botones en cuello y puños.',colors: 'Azul cielo, Azul marino, Rojo, Verde',
//     sizes: '34, 36, 38, 40, 42, 46',
//     category: 'Casual',
//     subcategory: 'Camisas',
//   },
//   {
//     id: 7,
//     title: 'JUEGO DE PANTS COMPLETO',
//     description: 'Juego de pants completo marino sudadera con gorro, cierre y bolsa laterales. Pantalón recto con jareta y resorte en cintura, bolsas laterales y bolsa trasera.',colors: 'Acero, Amarillo, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Café, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Hueso, Jade, jaspe, Kiwi, Lila, Mango, Menta, Morado, Mostaza, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Stoned, Verde, Verde esmeralda, Verde limón, Verde militar, Vino',
//     sizes: 'CH, MD, GD, XG',
//     category: 'Casual',
//     subcategory: 'Pantalones',
//   },
//   {
//     id: 8,
//     title: 'PANTALÓN DE GABARDINA 100% ALG COMBINADO CON BOLSAS DE CARGO',
//     description: 'Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo, corte amplio.',colors: 'Acero, Amarillo, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Café, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Hueso, Jade, jaspe, Kiwi, Lila, Mango, Menta, Morado, Mostaza, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Stoned, Verde, Verde esmeralda, Verde limón, Verde militar, Vino',
//     sizes: '28, 30, 32, 34, 36, 38, 40, 48',
//     category: 'Casual',
//     subcategory: 'Pantalones',
//   },
//   {
//     id: 8,
//     title: 'PANTALÓN DE GABARDINA LIGERA CON FILO EN BOLSAS',
//     description: 'Pantalón confeccionado en tela gabardina ligera con bolsas laterales y bolas de cargo, corte amplio.',colors: 'Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo, Verde militar',
//     sizes: '28, 30, 32, 34, 36, 38, 40, 49',
//     category: 'Casual',
//     subcategory: 'Pantalones',
//   },
//   {
//     id: 9,
//     title: 'PANTALÓN DE MEZCLILLA CABALLERO BOGGI 14 OZ',
//     description: 'Pantalón de mezclilla 100% Alg corte clásico, ancho de pierna ancho.',colors: 'Stoned',
//     sizes: '28, 30, 32, 34, 36, 38, 40, 42',
//     category: 'Casual',
//     subcategory: 'Pantalones',
//   },
//   {
//     id: 10,
//     title: 'PANTALÓN DE MEZCLILLA CABALLERO BOGGI 14 OZ CON REFLEJANTE',
//     description: 'Pantalón de mezclilla 100% Alg corte clásico, ancho de pierna ancho.',colors: 'Stoned',
//     sizes: '34, 36, 38, 40, 42, 44',
//     category: 'Casual',
//     subcategory: 'Pantalones',
//   },
//   {
//     id: 12,
//     title: 'PANTALÓN DE MEZCLILLA CABALLERO MARVI 14 OZ',
//     description: '  Pantalón de mezclilla 100% Alg corte clasico, ancho de pierna ancho.',
//     category: 'Casual',
//     subcategory: 'Pantalones',
//     sizes: '28, 30, 32, 34, 36, 38, 40, 44',colors: 'Stoned',
//   },
//   {
//     id: 13,
//     title: 'PANTALÓN GABARDINA 100% ALG CON BOLSAS DE CARGO REFLEJANTE',
//     description: 'Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo, corte amplio.',
//     category: 'Casual',
//     subcategory: 'Pantalones',colors: 'Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo, Verde militar',
//     sizes: '34, 36, 38, 40, 42, 44'
//   },
//   {
//     id: 14,
//     title: 'PANTALÓN GABARDINA 100% ALG CON BOLSAS DE CARGO Y REFLEJANTdescription:',
//     description: 'Pantalón confeccionado en tela gabardina 100 % Alg con bolsas laterales y bolas de cargo, corte amplio. Con reflejante en piernas.',colors: 'Azul marino, Blanco, Gris Oxford, Naranja, Negro, Rojo, Stoned, Verde militar',
//     sizes: '34, 36, 38, 40, 42, 44',
//     category: 'Casual',
//     subcategory: 'Pantalones',
//   },
//   {
//     id: 15,
//     title: 'PANTALÓN RISTOP CABALLERO CON BOLSAS DE CARGO REPELENTE',
//     description: 'Pantalón confeccionado en tela ristop repelente al agua con bolsas laterales y bolas de cargo, corte amplio.',
//     category: 'Casual',
//     subcategory: 'Pantalones',colors: 'Azul marino, Gris Oxford, Negro',
//     sizes: '34, 36, 38, 40, 42, 44',
//   }
// ]

// // {
// //   id: 2,
// //   title: '',
// //   description: '',
// //   colors: '',
// //   sizes: '',
// //   category: '',
// //   subcategory: '',
// // },
  {
    id: 13190,
    title: "Camisola de Mezclilla 100% Alg 10 oz",
    description: "Camisola de Mezclilla 100% Algodón de 10 oz manga larga, 2 bolsas al frente, botones visibles u ocultos, botón en mangas.>Camisola de Mezclilla 100% Algodón de 10 oz manga larga, 2 bolsas al frente, botones visibles u ocultos, botón en mangas.,",
    category: "Industrial",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1347.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1348.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1351.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1349.png",
  },
  {
    id: 13191,
    title: "Camisola de Gabardina 100% Alg",
    description: "Camisola de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas.>Camisola de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas.,",
    category: "Industrial",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1357.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1357.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1358.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1359.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1360.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13192,
    title: "Camisola de Gabardina 100% Alg con reflejante en mangas y espalda",
    description: "Camisola de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Con reflejante en mangas y espalda.>Camisola de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Con reflejante en mangas y espalda.,",
    category: "Industrial",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1357.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1358.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1356.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13193,
    title: "Camisola de Gabardina 100% Alg, combinada, manga corta Personalizada",
    description: "Camisola de Gabardina 100% Algodón, manga corta, 1 bolsa normal al frente y bolsa pequeña para credencial ,botones visibles u ocultos. >Camisola de Gabardina 100% Algodón, manga corta, 1 bolsa normal al frente y bolsa pequeña para credencial ,botones visibles u ocultos. ,",
    category: "Industrial",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1361.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1362.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1363.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13194,
    title: "Camisola tipo Racing 60% Alg - 40% Pol",
    description: "Camisola de Gabardina 60% Alg-40% Pol, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Con reflejante en mangas y espalda.>Camisola de Gabardina 60% Alg-40% Pol, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Con reflejante en mangas y espalda.,",
    category: "Industrial",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1364.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1365.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1366.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13195,
    title: "Camisola tipo Racing 100% Algodón",
    description: "Camisola de Gabardina 60% Alg-40% Pol, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Con reflejante en mangas y espalda.>Camisola de Gabardina 60% Alg-40% Pol, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Con reflejante en mangas y espalda.,",
    category: "Industrial",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1367.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1368.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1370.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1369.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13196,
    title: "Bata de Gabardina 100% Algodón",
    description: "Bata de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Ajustador en espalda.>Bata de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Ajustador en espalda.,",
    category: "Industrial",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1599.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1600.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13197,
    title: "Bata de Gabardina Ligera 50% Alg - 50% Pol",
    description: "Bata de Gabardina 50% Alg - 50% Pol, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Ajustador en espalda.>Bata de Gabardina 50% Alg - 50% Pol, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Ajustador en espalda.,",
    category: "Industrial",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1601.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1602.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13198,
    title: "Bata de Gabardina 100% Algodón con reflejante",
    description: "Bata de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Resorte en espalda. Reflejante>Bata de Gabardina 100% Algodón, manga larga, 2 bolsas al frente, botones visibles u ocultos, botón en mangas. Resorte en espalda. Reflejante,",
    category: " Industrial",
    sizes: " Novedades\"",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1603.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1604.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13199,
    title: "Bata de Gabardina 100% Algodón",
    description: "Bata de Gabardina 100% Algodón, manga larga, 2 bolsas al frente,botones visibles u ocultos, botón en mangas. Ajustador en espalda.>Bata de Gabardina 100% Algodón, manga larga, 2 bolsas al frente, botones visibles u ocultos, botón en mangas. Ajustador en espalda.,",
    category: "Industrial",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1605.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1607.png",colors: "Azul cielo, Azul marino, Azul Rey, Beige, Blanco, Gris Jaspe, Gris Oxford, Naranja, Negro, Rojo, Verde esmeralda, Verde militar",
  },
  {
    id: 13200,
    title: "Camisa Casual tela oxford 65% Alg - 35% Pol",
    description: "Camisa Casual confeccionada en tela Oxford 65% Alg - 35% Pol.\n\\n\n\\nManga larga, botones en cuello y puños.\n\\n\n\\nCon Pie de cuello y puños mil rayas / marino.",
    category: "Casual > Camisas, Casual",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1371-1.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1372.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1371-1.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1372-1.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1501.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1502.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1503.png",colors: "Azul cielo, Azul marino, Blanco, Rosa",
  },
  {
    id: 13201,
    title: "Blusa Casual tela oxford 65% Alg - 35% Pol",
    description: "Blusa Casual confeccionada en tela Oxford 65% Alg - 35% Pol.\n\\n\n\\nAsiluetada, manga larga, botones en puños.\n\\n\n\\nCon Pie de cuello y puños mil rayas / marino.",
    category: "Casual > Camisas, Casual",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1374.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1376.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1377.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1504.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1505.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1506.png",colors: "Azul cielo, Azul marino, Blanco, Rosa",
  },
  {
    id: 13202,
    title: "Camisa Casual tela oxford mil rayas 65% Alg - 35% Pol",
    description: "Camisa Casual confeccionada en tela Oxford 65% Alg - 35% Pol.\n\\n\n\\nManga larga, botones en cuello y puños.",
    category: "Casual > Camisas, Casual",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1495.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1496.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1497.png",colors: "Azul cielo, Azul marino, Rojo, Verde",
  },
  {
    id: 13203,
    title: "Blusa Casual tela oxford mil rayas 65% Alg - 35% Pol",
    description: "Blusa Casual confeccionada en tela Oxford 65% Alg - 35% Pol.\n\\n\n\\nAsiluetada, manga larga, botones en puños.",
    category: "Casual > Camisas, Casual",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1498.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1499.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1500.png",colors: "Azul cielo, Azul marino, Rojo, Verde",
  },
  {
    id: 13204,
    title: "Camisa Casual tela oxford 65% Alg - 35% Pol",
    description: "Camisa Casual confeccionada en tela Oxford 65% Alg - 35% Pol.\n\\n\n\\nManga corta, botones en cuello y puños.\n\\n\n\\nCon Pie de cuello y puños mil rayas / marino.",
    category: "Casual > Camisas, Casual",
    sizes: "34, 36, 38, 40, 42, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1507.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1508.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1509.png",colors: "Azul celeste, Azul marino, Blanco, Rosa",
  },
  {
    id: 13205,
    title: "Blusa Casual tela oxford 65% Alg - 35% Pol",
    description: "Blusa Casual confeccionada en tela Oxford 65% Alg - 35% Pol.\n\\n\n\\nAsiluetada, manga corta, botones en puños.\n\\n\n\\nCon Pie de cuello y puños mil rayas / marino.",
    category: "Casual > Camisas, Casual",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1510.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1511.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1512.png",colors: "Azul celeste, Azul marino, Blanco, Rosa",
  },
  {
    id: 13206,
    title: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol.\n\\n\n\\nManga corta, aletilla combinada",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1379.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1380.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1381.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13207,
    title: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol.\n\\n\n\\nManga corta, aletilla combinada",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1382.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1383.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1385.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1384.png",colors: "Acero, Amarillo, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Stoned, Vino",
  },
  {
    id: 13208,
    title: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol.\n\\n\n\\nManga larga.",
    category: "Casual, Novedades, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1389.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1390.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1392.png",colors: "Acero, Amarillo, Aqua, Azul celeste, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13209,
    title: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol.\n\\n\n\\nManga larga, aletilla combinada",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1386.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1387.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1388.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13210,
    title: "Playera cuello de tortuga Unisex",
    description: "Playera cuello de tortuga confeccionada en tela interlok en manga larga",
    category: "Casual",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1393.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1394.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1395.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13211,
    title: "Playera cuello redondo",
    description: "Playera cuello redondo confeccionada en tela interlok en manga corta",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1396.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1397.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1398.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Bandera, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13212,
    title: "Playera cuello \"V\"",
    description: "Playera cuello \"V\" confeccionada en tela interlok en manga corta",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1399.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1400.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1401.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13213,
    title: "Playera cuello \"V\" con reflejante",
    description: "Playera cuello \"V\" confeccionada en tela interlok en manga corta con reflejante",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1403.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1406.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1405.png",colors: "Acero, Amarillo, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13214,
    title: "Playera Dry fit cuello redondo",
    description: "Playera cuello redondo confeccionada en tela dry fit en manga corta",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1407.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1408.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1409.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13215,
    title: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol\n\\n\n\\nManga corta, aletilla combinada",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1410.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13216,
    title: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol.\n\\n\n\\nManga corta, aletilla combinada\n\\n\n\\nReflejante en espalda",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1410.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1411.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1412.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13217,
    title: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol.\n\\n\n\\nManga corta, aletilla combinada",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1413.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1414.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1415.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13218,
    title: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol",
    description: "Playera tipo polo dama confeccionada en 50% Alg - 50% Pol.\n\\n\n\\nManga corta, aletilla combinada",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1416.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1417.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1418.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13219,
    title: "Playera de Dama cuello \"V\" combinada",
    description: "Playera de Dama cuello \"V\" confeccionada en tela interlok en manga corta combinada con 2 tonos",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1419.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1420.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1421.png",colors: "Acero, Aqua, Azul celeste, Azul cielo, Azul marino, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13220,
    title: "Sudadera confeccionada en felpa 50% Alg - 50% Pol",
    description: "Sudadera Unisex confeccionada en felpa 50% Alg - 50% Pol\n\\n\n\\nCombinada en cuello, reflejante en espalda\n\\n\n\\nForro polar",
    category: "Deportivos, Deportivos > Sudaderas",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1422.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1423.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1424.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Café, Canario, Fiusha, Hueso, Jade, Mostaza, Naranja, Negro, Rojo, Rosa, Verde militar, Vino",
  },
  {
    id: 13221,
    title: "Sudadera confeccionada en felpa 50% Alg - 50% Pol",
    description: "Sudadera Unisex confeccionada en felpa 50% Alg - 50% Pol\n\\n\n\\nCombinada, forro polar",
    category: "Deportivos, Deportivos > Sudaderas",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1425.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1426.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1427.png",colors: "Azul marino, Azul Rey, Blanco, Café, Canario, Fiusha, Hueso, Jade, Mostaza, Naranja, Negro, Rojo, Rosa, Verde militar, Vino",
  },
  {
    id: 13222,
    title: "Sudadera confeccionada en felpa 50% Alg - 50% Pol con gorro, canguera y reflejante",
    description: "Sudadera Unisex confeccionada en felpa 50% Alg - 50% Pol\n\\n\n\\nForro polar con gorro, canguera y reflejante",
    category: "Deportivos, Deportivos > Sudaderas",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1428.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1429.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1430.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Café, Canario, Fiusha, Hueso, Jade, Mostaza, Naranja, Negro, Rojo, Rosa, Verde militar, Vino",
  },
  {
    id: 13223,
    title: "Sudadera confeccionada en felpa 50% Alg - 50% Pol con capucha",
    description: "Sudadera Unisex confeccionada en felpa 50% Alg - 50% Pol forro polar, con costuras externa y capucha",
    category: "Deportivos, Deportivos > Sudaderas",
    sizes: "CH, GD, MD, XG",
    images: "",
    colors: "Amarillo, Azul marino, Azul Rey, Blanco, Café, Canario, Fiusha, Hueso, Jade, Mostaza, Naranja, Negro, Rojo, Rosa, Verde militar, Vino",
  },
  {
    id: 13224,
    title: "Sudadera confeccionada en felpa 50% Alg - 50% Pol cuello alto",
    description: "Sudadera Unisex confeccionada en felpa 50% Alg - 50% Pol\n\\n\n\\nForro polar con cuello alto y bolsas laterales",
    category: "Deportivos, Deportivos > Sudaderas",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1434.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1435.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1436.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1433.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Café, Canario, Fiusha, Hueso, Jade, Mostaza, Naranja, Negro, Rojo, Rosa, Verde militar, Vino",
  },
  {
    id: 13225,
    title: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol Combinada",
    description: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol\n\\n\n\\nManga corta, aletilla y costados combinados",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1437.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1438.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1439.png",colors: "Acero, Aqua, Azul celeste, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13226,
    title: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol Combinada",
    description: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol\n\\n\n\\nManga corta, aletilla y costados combinados",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1440.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1441.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1442.png",colors: "Acero, Amarillo, Aqua, Azul celeste, Azul cielo, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13227,
    title: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol Combinada",
    description: "Playera tipo polo caballero confeccionada en 50% Alg - 50% Pol\n\\n\n\\nManga corta, aletilla y frente combinado",
    category: "Casual, Casual > Playeras",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1443.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1445.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1444.png",colors: "Acero, Aqua, Azul celeste, Azul marino, Azul Rey, Bandera, Beige, Blanco, Botella, Canario, Chocolate, Coral, Fiusha, Gris Jaspe, Gris Oxford, Jade, Kiwi, Lila, Mango, Menta, Morado, Naranja, Negro, Paja, Pastel, Perla, Pistache, Plumbago, Rojo, Rosa, Vino",
  },
  {
    id: 13228,
    title: "Chamarra Timberland combinada forro polar",
    description: "Chamarra confeccionada en tela timberland combinada con forro polar.\n\\n\n\\nResorte en mangas y cintura, bolsas laterales.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos, Novedades",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1446.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1447.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1448.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13229,
    title: "Chamarra Capitonada Rayas forro polar",
    description: "Chamarra capitonada a rayas confeccionada en tela nylon.\n\\n\n\\nForro polar y cardigan en mangas, bolsas laterales.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1449.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1450.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1451.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13230,
    title: "Chamarra Timberland tipo cazadora forro polar",
    description: "Chamarra confeccionada en tela timberland tipo cazadora.\n\\n\n\\nForro polar resorte en mangas, bolsas laterales.\n\\n\n\\nGorro desmontable",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1452.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1453.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1454.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Naranja, Negro, Rojo",
  },
  {
    id: 13231,
    title: "Chamarra Timberland combinada forro polar",
    description: "Chamarra confeccionada en tela timberland con filos de color.\n\\n\n\\nForro polar resorte en mangas y cintura, bolsas laterales.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1455.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1456.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1457.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Naranja, Negro, Rojo",
  },
  {
    id: 13232,
    title: "Chamarra timberland combinada forro polar",
    description: "Chamarra confeccionada en tela timberland tipo cazadora con forro polar.\n\\n\n\\nResorte en mangas, resorte en cintura bolsas laterales.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1458.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1459.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1461.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Naranja, Negro, Rojo",
  },
  {
    id: 13233,
    title: "Chamarra Timberland tipo cazadora forro polar con reflejante",
    description: "Chamarra confeccionada en tela timberland tipo cazadora\n\\n\n\\nForro polar resorte en mangas, bolsas laterales.\n\\n\n\\nGorro desmontable y reflejante.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1465.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1466.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1467.png",colors: "Amarillo, Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro",
  },
  {
    id: 13234,
    title: "Chamarra Nylon cierre metálicos forro sportok",
    description: "Chamarra confeccionada en Nylon forro sportok, cierres metálicos.\n\\n\n\\nCardigan en puños y cintura, con bolsas de cierre.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1468.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1469.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1470.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13235,
    title: "Chamarra Dama Tela diablo",
    description: "Chamarras de dama confeccionada en tela diablo con piola en combinación.\n\\n\n\\nRepelente al agua. Asiluetada",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1471.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1472.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1473.png",colors: "",
  },
  {
    id: 13236,
    title: "Chamarra Caballero Tela diablo",
    description: "Chamarra caballero confeccionada en tela diablo repelente al agua.\n\\n\n\\nCon filo reflejante, bolsas laterales con cierre.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1474.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1475.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1476.png",colors: "Amarillo, Azul marino, Azul Rey, Gris Oxford, Negro, Rojo, Vino",
  },
  {
    id: 13237,
    title: "Chamarra Caballero Polar combinada forro polar tipo cazadora",
    description: "Chamarra caballero confeccionada en tela de polar, bolsas laterales con cierre.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1425-1.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1426-1.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1427-1.png",colors: "Amarillo, Azul marino, Azul Rey, Gris Oxford, Negro, Rojo, Vino",
  },
  {
    id: 13238,
    title: "Chamarra Tela tiburón con mangas desmontables forro polar",
    description: "Chamarra caballero confeccionada Tela tiburón forro polar y 2 bolsas laterales.\n\\n\n\\nMangas desmontables.\n\\n\n\\nReflejante frente y espalda, cardigan en puños y cintura",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1480.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1481.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1482.png",colors: "Amarillo, Azul Rey, Gris Oxford, Negro, Rojo, Vino",
  },
  {
    id: 13239,
    title: "Chamarra Tela tiburon con  forro polar y reflejante tipo motociclista",
    description: "Chamarra caballero confeccionada Tela tiburon repelente.\n\\n\n\\nForro polar y 2 bolsas laterales.\n\\n\n\\nReflejante frente y espalda.",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1483.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1484.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1485.png",colors: "Naranja, Negro, Verde limón",
  },
  {
    id: 13240,
    title: "Chamarra Tela tiburón con reflejante forro polar",
    description: "Chamarra caballero confeccionada Tela tiburón repelente.\n\\n\n\\nForro polar y 2 bolsas laterales.\n\\n\n\\nReflejante frente y espalda, cardigan en puños y cintura",
    category: "Chamarras y chalecos > Chamarras, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1486.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1487.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1488.png",colors: "Naranja, Negro, Verde limón",
  },
  {
    id: 13241,
    title: "Chaleco capitonado nylon forro polar",
    description: "Chaleco confeccionado en tela nylon con forro polar y bolsas laterales.",
    category: "Chamarras y chalecos > Chalecos, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1513.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1515.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13242,
    title: "Chaleco Gabardina 100% Alg capitonado en hombros tipo reportero",
    description: "Chaleco confeccionado en gabardina 100% Algodón.\n\\n\n\\nCapitonado rombos en hombros.\n\\n\n\\n5 bolsas tipo reportero, ajustable en cintura.",
    category: "Chamarras y chalecos > Chalecos, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1517.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1518.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13243,
    title: "Chaleco capitonado nylon forro polar",
    description: "Chaleco confeccionado en tela nylon con forro polar y bolsas laterales.",
    category: "Chamarras y chalecos > Chalecos, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1521.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1522.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1523.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13244,
    title: "Chaleco tela diablo piola fluoresente verde",
    description: "Chaleco confeccionado en tela diablo repelente al agua.\n\\n\n\\nCon piola en combinación, bolsas laterales.",
    category: "Chamarras y chalecos > Chalecos, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1524.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1525.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1526.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1526-1.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13245,
    title: "Chaleco timberland forro capitonado",
    description: "Chaleco confeccionado en tela timberland con forro capitonado 5 bolsas tipo reportero>Chaleco confeccionado en tela timberland con forro capitonado 5 bolsas tipo reportero,",
    category: " Chamarras y chalecos\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1536.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1536.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1537.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1538.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13246,
    title: "Chaleco capitonado rombos combinado en espalda",
    description: "Chaleco confeccionado en tela nylon con espalda combinado en espalda en tela polar con bolsas laterales.",
    category: "Chamarras y chalecos > Chalecos, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1528.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1529.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1530.png",colors: "",
  },
  {
    id: 13248,
    title: "Chaleco dama capitonado rombos microfibra forro polar",
    description: "Chaleco confeccionado en tela de microfibra dama asiluetado capitonada en rombos con reflejante al frente y bolsas laterales>Chaleco confeccionado en tela de microfibra dama asiluetado capitonada en rombos.</span>\n\\n\n\\nCon gamusa en hombros y espalda.",
    category: "Chamarras y chalecos > Chalecos, Chamarras y chalecos",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1536.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1537.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1538.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13249,
    title: "Chaleco dama capitonado rombos nylon forro polar",
    description: "Chaleco dama asiluetada confeccionado en tela nylon con forro polar y bolsas laterales.>Chaleco dama asiluetada confeccionado en tela nylon con forro polar y bolsas laterales.,",
    category: " Chamarras y chalecos\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1539.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1540.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13250,
    title: "Chaleco Gabardina 100% Alg tipo reportero 5 bolsas",
    description: "Chaleco de gabardina 100% Alg tipo reportero con 5 bolsas >Chaleco de gabardina 100% Alg tipo reportero con 5 bolsas.</span>\n\\n\n\\nCon reflejante en bolsas.",
    category: "Seguridad > Chalecos, Novedades, Seguridad",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1542.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1543.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1544.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13251,
    title: "Chaleco Gabardina 100% Alg combinado tipo reportero",
    description: "Chaleco de gabardina 100% Alg tipo reportero.\n\\n\n\\nCon 9 bolsas y reflejante frente y espalda",
    category: "Seguridad > Chalecos, Seguridad",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1545.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1546.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1547.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13252,
    title: "Chaleco timberland forro polar 5 bolsas con reflejante",
    description: "Chaleco de timberland forro polar tipo reportero con 5 bolsas y reflejante>Chaleco de timberland forro polar tipo reportero.</span>\n\\n\n\\nChaleco de timberland forro polar tipo reportero con 5 bolsas y reflejante>Con 5 bolsas y reflejante,",
    category: " Seguridad\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1548.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1549.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1550.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13253,
    title: "Chaleco timberland forro polar 5 bolsas con gorro",
    description: "Chaleco de timberland forro polar tipo reportero con 5 bolsas y reflejante>Chaleco de timberland forro polar tipo reportero.</span>\n\\n\n\\nChaleco de timberland forro polar tipo reportero con 5 bolsas y reflejante>Con 5 bolsas y reflejante.</span>\n\\n\n\\nCon gorro desmontable.",
    category: "Seguridad > Chalecos, Seguridad",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1551.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1553.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1554.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13254,
    title: "Chaleco Gabardina ligera  con reflejante ajustable",
    description: "Chaleco de gabardina ligera tipo reportero con 5 bolsas ajustable>Chaleco de gabardina ligera de seguridad con 5 bolsas ajustable</span>\n\\n\n\\nCon reflejante",
    category: "Seguridad > Chalecos, Seguridad",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1555.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1556.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1557.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo, Verde militar",
  },
  {
    id: 13255,
    title: "Chaleco de seguridad calado con cinta reflejante estampado",
    description: "Chaleco de tela ligera con 2 bolsas al frente y reflejante en frente y espala>Chaleco de seguridad  tela ligera con 2 bolsas al frente y reflejante en frente y espalda,",
    category: " Seguridad\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1558.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1559.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1560.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13256,
    title: "Pantalón de mezclilla caballero Boggi 14 oz",
    description: "Pantalón de mezclilla 100% Alg corte clásico 14 oz.\n\\n\n\\n&nbsp;",
    category: "Casual, Casual > Pantalones",
    sizes: "28, 30, 32, 34, 36, 38, 40, 42",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1566-wpp1594303423821.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1565-wpp1594303469299.png",colors: "Stoned",
  },
  {
    id: 13257,
    title: "Pantalón de mezclilla caballero Boggi 14 oz con reflejante",
    description: "Pantalón de mezclilla 100% Alg corte clasico, ancho de pierna ancho>Pantalón de mezclilla 100% Alg corte clasico con reflejante.,",
    category: " Casual > Pantalones\"",
    sizes: "28, 30, 32, 34, 36, 38, 40, 43",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1568-wpp1594303376860.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1570-wpp1594303293263.png",colors: "Stoned",
  },
  {
    id: 13258,
    title: "Pantalón de mezclilla caballero Marvi 14 oz",
    description: "Pantalón de mezclilla 100% Alg corte clasico, ancho de pierna ancho>Pantalón de mezclilla 100% Alg corte clasico.,",
    category: " Casual > Pantalones\"",
    sizes: "28, 30, 32, 34, 36, 38, 40, 44",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1572-wpp1594303199198.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1573-wpp1594303158517.png",colors: "Stoned",
  },
  {
    id: 13259,
    title: "Pantalón Ristop caballero con bolsas de cargo repelente",
    description: "Pantalón confeccionado en tela ristop repelente al agua con bolsas laterales y bolas de cargo, corte amplio.>Pantalón confeccionado en tela ristop repelente al agua con bolsas laterales y bolas de cargo, corte amplio.,",
    category: " Casual > Pantalones\"",
    sizes: "28, 30, 32, 34, 36, 38, 40, 45",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1579-wpp1594303018230.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1578-wpp1594303072893.png",colors: "Azul marino, Gris Oxford, Negro",
  },
  {
    id: 13260,
    title: "Pantalón Gabardina 100% Alg con bolsas de cargo y reflejante",
    description: "Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo, corte amplio. Con reflejante en piernas>Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo.</span>\n\\n\n\\nPantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo, corte amplio. Con reflejante en piernas>Corte amplio y reflejante en piernas,",
    category: " Casual > Pantalones\"",
    sizes: "28, 30, 32, 34, 36, 38, 40, 46",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1581-wpp1594302921181.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1583-wpp1594302839171.png",colors: "Azul marino, Blanco, Gris Oxford, Naranja, Negro, Rojo, Stoned, Verde militar",
  },
  {
    id: 13261,
    title: "Pantalón Gabardina 100% Alg con bolsas de cargo reflejante",
    description: "Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo, corte amplio. >Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolsas de cargo.</span>\n\\n\n\\nPantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo, corte amplio. >Corte amplio y reflejante.,",
    category: " Casual > Pantalones\"",
    sizes: "28, 30, 32, 34, 36, 38, 40, 47",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1578-wpp1594303072893.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1579-wpp1594303018230.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo, Verde militar",
  },
  {
    id: 13262,
    title: "Pantalón de gabardina 100% Alg combinado  con bolsas de cargo",
    description: "Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolas de cargo, corte amplio.>Pantalón confeccionado en tela gabardina 100% Alg con bolsas laterales y bolsas de cargo, corte amplio.,",
    category: " Casual > Pantalones\"",
    sizes: "28, 30, 32, 34, 36, 38, 40, 48",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1585-wpp1594302648665.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1587-wpp1594302541795.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo, Verde militar",
  },
  {
    id: 13263,
    title: "Pantalón de gabardina ligera con filo en bolsas",
    description: "Pantalón confeccionado en tela gabardina ligera con bolsas laterales y bolas de cargo, corte amplio.>Pantalón confeccionado en tela gabardina ligera con bolsas laterales.,",
    category: " Casual > Pantalones\"",
    sizes: "28, 30, 32, 34, 36, 38, 40, 49",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1593-wpp1594260809893.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1596-wpp1594260593765.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo, Verde militar",
  },
  {
    id: 13264,
    title: "Conjunto gabardina 100% alg combinado",
    description: "Camisola y pantalón de gabardina 100% Alg >Camisola y pantalón de gabardina 100% Alg combinado,",
    category: " Industrial > Personalizado\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1590-wpp1594261042718.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1589-wpp1594261090215.png",colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo, Verde militar",
  },
  {
    id: 13265,
    title: "Conjunto gabardina ligera combinado",
    description: "Chaleco y pantalón de gabardina ligera>Chaleco y pantalón de gabardina ligera</span>\n\\n\n\\nCamisola de gabardina tipo racing",
    category: "Personalizados > Conjuntos completos, Personalizados",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1598-wpp1594260480297.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1597-wpp1594260532955.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1594-wpp1594260765978.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1595-wpp1594260640874.png",colors: "Azul marino, Blanco, Gris Oxford, Naranja, Negro, Rojo, Stoned, Verde militar",
  },
  {
    id: 13266,
    title: "Camisola y pantalón mezclilla uso rudo",
    description: "Pantalón confeccionado en gabardina ligera corte amplio>Camisola y pantalón de mezlilla de 14 oz uso rudo.</span>\n\\n\n\\nReflejante en piernas.",
    category: "Médicos, Médicos > Pantalón",
    sizes: "28, 30, 32, 34, 36, 38, 40, 49",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1609-wpp1594260361126.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1612-wpp1594258892428.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1611-wpp1594258936303.png",colors: "Azul cielo, Blanco, Plumbago, Vino",
  },
  {
    id: 13267,
    title: "Overol con peto y tirantes gabardina 100% Alg",
    description: "Overol con peto y tirantes gabardina 100% Alg\n\\n\n\\nBolsas de cargo",
    category: "Industrial, Industrial > Overoles, Médicos > Overoles",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1591-wpp1594260953466.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1592-wpp1594260904863.png",
    colors: "Azul cielo, Blanco, Plumbago, Vino",
  },
  {
    id: 13268,
    title: "Bata dama asiluetado 100% Alg manga larga botones ocultos",
    description: "Bata de dama asiluetada 100% Alg corte largo con botones al frente y en puños, cinta trasera ajustable>Bata de dama asiluetada 100% Alg corte largo con botones al frente.</span>\n\\n\n\\nBata de dama asiluetada 100% Alg corte largo con botones al frente y en puños, cinta trasera ajustable>Resorte en puños, cinta trasera ajustable,",
    category: " Médicos\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1623-wpp1594258758297.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1621-wpp1594258789775.png",
    colors: "Azul cielo, Blanco, Plumbago, Vino",
  },
  {
    id: 13269,
    title: "Overol gabardina ligera con cierre",
    description: "Overol de gabardina ligera corte amplio, resorte en espalda botones y cierre ocultos>Overol de gabardina ligera corte amplio, resorte en espalda botones y cierre ocultos,",
    category: " Médicos > Overoles\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1624-wpp1594258528776.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1625-wpp1594258457870.png",
    colors: "Azul cielo, Blanco, Plumbago, Vino",
  },
  {
    id: 13270,
    title: "Filipina y pantalón de dama gabardina ligera",
    description: "Filipina y pantalón de gabardina ligera corte amplio, resorte en espalda botones y cierre ocultos>Filipina y pantalón de gabardina ligera corte amplio, resorte en espalda botones y cierre ocultos,",
    category: " Médicos\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1630-wpp1594258294125.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1631-wpp1594258259609.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1634-wpp1594258157831.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1633-wpp1594258218860.png",
    colors: "Azul cielo, Blanco, Plumbago, Vino",
  },
  {
    id: 13271,
    title: "Camisola y pantalón de gabardina personalizado",
    description: "Overol confeccionado en tela ristop repelente corte amplio, resorte en espalda botones y cierre ocultos con forro polar y gorro>Camisola y pantalón de gabardina 100% Alg personalizado.,",
    category: " Industrial > Overoles\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1576-wpp1594303116728.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1580-wpp1594302975623.png",
    colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13272,
    title: "Overol gabardina 100% Alg combinado",
    description: "Overol de gabardina 100% Alg corte amplio, resorte en espalda botones y cierre ocultos>Overol de gabardina 100% Alg corte amplio, resorte en espalda botones y cierre ocultos,",
    category: " Industrial > Overoles\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1628-wpp1594258662783.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1645-wpp1594258634598.png",
    colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13273,
    title: "Overol gabardina 100% Alg con reflejante",
    description: "Overol de gabardina 100% Alg corte amplio, resorte en espalda botones y cierre ocultos>Overol de gabardina 100% Alg corte amplio, resorte en espalda botones y cierre ocultos</span>\n\\n\n\\nCon reflejante",
    category: "Industrial, Industrial > Overoles",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1639-wpp1594258368154.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1643-wpp1594258327205.png",
    colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13274,
    title: "Overol gabardina 100% Alg combinado",
    description: "Overol de gabardina 100% Alg corte amplio, resorte en espalda botones y cierre ocultos>Overol de gabardina 100% Alg corte amplio, resorte en espalda botones y cierre ocultos,",
    category: " Industrial > Overoles\"",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1641-wpp1594258598321.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1642-wpp1594258569461.png",
    colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13275,
    title: "Overol gabardina 100% Alg Basico",
    description: "Overol de gabardina 100% Alg corte amplio, resorte en espalda botones y cierre ocultos",
    category: "Industrial, Industrial > Overoles",
    sizes: "CH, GD, MD, XG",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1647-wpp1594258723602.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1650-wpp1594258693477.png",
    colors: "Azul marino, Azul Rey, Blanco, Gris Oxford, Naranja, Negro, Rojo",
  },
  {
    id: 13305,
    title: "Camisola de Mezclilla 100% Alg 14 oz",
    description: "<div class=\"brz-root__container brz-reset-all\"></div><!-- version:1652960479 -->",
    category: "Industrial > Camisolas, Industrial",
    sizes: "",
    images: "http://grupodistext.com/wp-content/uploads/2020/06/DSC_1350.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1351.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1352.png, http://grupodistext.com/wp-content/uploads/2020/06/DSC_1349.png",
    colors: "Stoned",
  },
]